server:
  port: 8888
spring:
  activemq:
    broker-url: tcp://10.218.34.4:21616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false           #false = queue  true = topic

#自定义队列名称
myqueue: boot-active-queue
mytopic: boot-active-topic
